// Auto-generated by scripts/generate-toc.mjs — do not edit manually
import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "مقدمه",
    "items": [
      {
        "text": "پیش‌گفتار",
        "link": "/preface"
      }
    ]
  },
  {
    "text": "فصل‌ها",
    "items": [
      {
        "text": "فصل ۱: درک معماری اپلیکیشن‌های React",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-01"
          },
          {
            "text": "چرا معماری مهم است",
            "collapsed": true,
            "items": [
              {
                "text": "معماری به‌عنوان بنیان",
                "link": "/chapters/chapter-01#h2_16"
              },
              {
                "text": "هماهنگی و سرعت توسعه",
                "link": "/chapters/chapter-01#h2_17"
              },
              {
                "text": "سرعت از طریق شفافیت",
                "link": "/chapters/chapter-01#h2_18"
              },
              {
                "text": "اقتصاد معماری خوب",
                "link": "/chapters/chapter-01#h2_19"
              },
              {
                "text": "معماری و کیفیت محصول",
                "link": "/chapters/chapter-01#h2_20"
              }
            ],
            "link": "/chapters/chapter-01#h1_15"
          },
          {
            "text": "چالش معماری در React",
            "collapsed": true,
            "items": [
              {
                "text": "چگونه پروژه را ساختاربندی کنیم؟",
                "link": "/chapters/chapter-01#h2_22"
              },
              {
                "text": "چگونه اپلیکیشن را رندر کنیم؟",
                "link": "/chapters/chapter-01#h2_23"
              },
              {
                "text": "چگونه state را مدیریت کنیم؟",
                "link": "/chapters/chapter-01#h2_24"
              },
              {
                "text": "چگونه کامپوننت‌ها را استایل دهیم؟",
                "link": "/chapters/chapter-01#h2_25"
              },
              {
                "text": "چگونه data fetching را انجام دهیم؟",
                "link": "/chapters/chapter-01#h2_26"
              },
              {
                "text": "چگونه احراز هویت را پیاده‌سازی کنیم؟",
                "link": "/chapters/chapter-01#h2_27"
              },
              {
                "text": "چگونه اپلیکیشن React را تست کنیم؟",
                "link": "/chapters/chapter-01#h2_28"
              },
              {
                "text": "تصمیم متا",
                "link": "/chapters/chapter-01#h2_29"
              }
            ],
            "link": "/chapters/chapter-01#h1_21"
          },
          {
            "text": "اندیشیدن درباره تصمیم‌های معماری",
            "collapsed": true,
            "items": [
              {
                "text": "الگوهایی که معمولاً جواب نمی‌دهند",
                "link": "/chapters/chapter-01#h2_31"
              },
              {
                "text": "الگوهایی که معمولاً جواب می‌دهند",
                "link": "/chapters/chapter-01#h2_32"
              }
            ],
            "link": "/chapters/chapter-01#h1_30"
          },
          {
            "text": "برنامه‌ریزی اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "نیازمندی‌های کارکردی: چه کاری انجام می‌دهد",
                "link": "/chapters/chapter-01#h2_34"
              },
              {
                "text": "نیازمندی‌های غیرکارکردی: چگونه کار می‌کند",
                "link": "/chapters/chapter-01#h2_35"
              },
              {
                "text": "مدل داده",
                "collapsed": true,
                "items": [
                  {
                    "text": "تصمیم‌های معماری",
                    "link": "/chapters/chapter-01#h3_37"
                  },
                  {
                    "text": "ساختار پروژه: مبتنی بر feature",
                    "link": "/chapters/chapter-01#h3_38"
                  },
                  {
                    "text": "استراتژی رندر: hybrid",
                    "link": "/chapters/chapter-01#h3_39"
                  },
                  {
                    "text": "مدیریت state: چندلایه",
                    "link": "/chapters/chapter-01#h3_40"
                  },
                  {
                    "text": "استایل: Tailwind CSS + BaseUI",
                    "link": "/chapters/chapter-01#h3_41"
                  },
                  {
                    "text": "احراز هویت: مبتنی بر Cookie",
                    "link": "/chapters/chapter-01#h3_42"
                  },
                  {
                    "text": "تست: pragmatic",
                    "link": "/chapters/chapter-01#h3_43"
                  }
                ],
                "link": "/chapters/chapter-01#h2_36"
              }
            ],
            "link": "/chapters/chapter-01#h1_33"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-01#h1_44"
          }
        ]
      },
      {
        "text": "فصل ۲: راه‌اندازی و ساختار پروژه",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-02"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-02#h1_48"
          },
          {
            "text": "انتخاب meta framework برای پروژه",
            "collapsed": true,
            "items": [
              {
                "text": "meta framework چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-02#h2_50"
              },
              {
                "text": "مسائلی که حل می‌کنند",
                "link": "/chapters/chapter-02#h2_51"
              },
              {
                "text": "چشم‌انداز meta frameworkهای React",
                "collapsed": true,
                "items": [
                  {
                    "text": "Next.js",
                    "link": "/chapters/chapter-02#h3_53"
                  },
                  {
                    "text": "React Router (در حالت framework)",
                    "link": "/chapters/chapter-02#h3_54"
                  },
                  {
                    "text": "TanStack Start",
                    "link": "/chapters/chapter-02#h3_55"
                  }
                ],
                "link": "/chapters/chapter-02#h2_52"
              },
              {
                "text": "انتخاب درست",
                "link": "/chapters/chapter-02#h2_56"
              },
              {
                "text": "چرا از React Router استفاده می‌کنیم",
                "link": "/chapters/chapter-02#h2_57"
              },
              {
                "text": "شروع کار با React Router",
                "link": "/chapters/chapter-02#h2_58"
              }
            ],
            "link": "/chapters/chapter-02#h1_49"
          },
          {
            "text": "مرور راه‌اندازی build tool",
            "collapsed": true,
            "items": [
              {
                "text": "Vite چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-02#h2_60"
              },
              {
                "text": "نحوه کار Vite با React Router",
                "link": "/chapters/chapter-02#h2_61"
              },
              {
                "text": "پیکربندی Vite ما",
                "link": "/chapters/chapter-02#h2_62"
              }
            ],
            "link": "/chapters/chapter-02#h1_59"
          },
          {
            "text": "مرور راه‌اندازی type-checking",
            "collapsed": true,
            "items": [
              {
                "text": "TypeScript چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-02#h2_64"
              },
              {
                "text": "نحوه کار TypeScript",
                "link": "/chapters/chapter-02#h2_65"
              },
              {
                "text": "پیکربندی TypeScript ما",
                "link": "/chapters/chapter-02#h2_66"
              },
              {
                "text": "تولید type در React Router",
                "link": "/chapters/chapter-02#h2_67"
              },
              {
                "text": "اجرای بررسی‌های TypeScript",
                "link": "/chapters/chapter-02#h2_68"
              }
            ],
            "link": "/chapters/chapter-02#h1_63"
          },
          {
            "text": "مرور راه‌اندازی linting",
            "collapsed": true,
            "items": [
              {
                "text": "linting چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-02#h2_70"
              },
              {
                "text": "مرور ESLint",
                "link": "/chapters/chapter-02#h2_71"
              },
              {
                "text": "پیکربندی ESLint ما",
                "link": "/chapters/chapter-02#h2_72"
              },
              {
                "text": "اجرای ESLint",
                "link": "/chapters/chapter-02#h2_73"
              }
            ],
            "link": "/chapters/chapter-02#h1_69"
          },
          {
            "text": "مرور راه‌اندازی formatting",
            "collapsed": true,
            "items": [
              {
                "text": "code formatting چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-02#h2_75"
              },
              {
                "text": "نحوه کار Prettier",
                "link": "/chapters/chapter-02#h2_76"
              },
              {
                "text": "پیکربندی Prettier",
                "link": "/chapters/chapter-02#h2_77"
              }
            ],
            "link": "/chapters/chapter-02#h1_74"
          },
          {
            "text": "مرور راه‌اندازی pre-commit checks",
            "collapsed": true,
            "items": [
              {
                "text": "pre-commit hook چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-02#h2_79"
              },
              {
                "text": "نحوه کار pre-commit hookها",
                "link": "/chapters/chapter-02#h2_80"
              },
              {
                "text": "workflow پیش از commit ما",
                "link": "/chapters/chapter-02#h2_81"
              },
              {
                "text": "اجرای pre-commit checks",
                "link": "/chapters/chapter-02#h2_82"
              }
            ],
            "link": "/chapters/chapter-02#h1_78"
          },
          {
            "text": "مرور ساختار پروژه",
            "collapsed": true,
            "items": [
              {
                "text": "ساختار پروژه چیست و چرا مهم است؟",
                "link": "/chapters/chapter-02#h2_84"
              },
              {
                "text": "رویکردهای مختلف به ساختار پروژه",
                "collapsed": true,
                "items": [
                  {
                    "text": "ساختار بر اساس نوع فایل",
                    "link": "/chapters/chapter-02#h3_86"
                  },
                  {
                    "text": "ساختار مبتنی بر feature",
                    "link": "/chapters/chapter-02#h3_87"
                  }
                ],
                "link": "/chapters/chapter-02#h2_85"
              },
              {
                "text": "چرا ساختار feature-based را انتخاب کردیم",
                "link": "/chapters/chapter-02#h2_88"
              },
              {
                "text": "جریان کد",
                "collapsed": true,
                "items": [
                  {
                    "text": "Application (سطح بالا)",
                    "link": "/chapters/chapter-02#h3_90"
                  },
                  {
                    "text": "Featureها (سطح میانی)",
                    "link": "/chapters/chapter-02#h3_91"
                  },
                  {
                    "text": "ابزارهای مشترک (سطح پایین)",
                    "link": "/chapters/chapter-02#h3_92"
                  },
                  {
                    "text": "چرا این موضوع مهم است",
                    "link": "/chapters/chapter-02#h3_93"
                  }
                ],
                "link": "/chapters/chapter-02#h2_89"
              },
              {
                "text": "اعمال ساختار پروژه با ESLint",
                "collapsed": true,
                "items": [
                  {
                    "text": "محدودیت ۱: ابزارهای مشترک باید مستقل بمانند",
                    "link": "/chapters/chapter-02#h3_95"
                  },
                  {
                    "text": "محدودیت ۲: featureها نمی‌توانند از app import کنند",
                    "link": "/chapters/chapter-02#h3_96"
                  },
                  {
                    "text": "محدودیت ۳: وابستگی‌های feature صریح و کنترل‌شده هستند",
                    "link": "/chapters/chapter-02#h3_97"
                  },
                  {
                    "text": "چرا این موضوع مهم است",
                    "link": "/chapters/chapter-02#h3_98"
                  }
                ],
                "link": "/chapters/chapter-02#h2_94"
              },
              {
                "text": "ESLint در عمل",
                "link": "/chapters/chapter-02#h2_99"
              }
            ],
            "link": "/chapters/chapter-02#h1_83"
          },
          {
            "text": "مرور راه‌اندازی environment variableها",
            "collapsed": true,
            "items": [
              {
                "text": "environment variable چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-02#h2_101"
              },
              {
                "text": "سیستم environment variable ما",
                "link": "/chapters/chapter-02#h2_102"
              },
              {
                "text": "راه‌اندازی environment variableها",
                "link": "/chapters/chapter-02#h2_103"
              }
            ],
            "link": "/chapters/chapter-02#h1_100"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-02#h1_104"
          }
        ]
      },
      {
        "text": "فصل ۳: ساخت و مستندسازی کامپوننت‌ها",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-03"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-03#h1_108"
          },
          {
            "text": "آناتومی یک کامپوننت",
            "collapsed": true,
            "items": [
              {
                "text": "کامپوننت چیست؟",
                "link": "/chapters/chapter-03#h2_110"
              },
              {
                "text": "استفاده از کامپوننت",
                "link": "/chapters/chapter-03#h2_111"
              }
            ],
            "link": "/chapters/chapter-03#h1_109"
          },
          {
            "text": "ساخت کتابخانه کامپوننت",
            "collapsed": true,
            "items": [
              {
                "text": "کتابخانه کامپوننت چیست و چرا به آن نیاز داریم؟",
                "link": "/chapters/chapter-03#h2_113"
              },
              {
                "text": "رویکردهای مختلف به کتابخانه کامپوننت",
                "collapsed": true,
                "items": [
                  {
                    "text": "گزینه ۱: نصب پکیج (Material-UI, Ant Design, Chakra UI, Mantine)",
                    "link": "/chapters/chapter-03#h3_115"
                  },
                  {
                    "text": "گزینه ۲: ساخت از صفر",
                    "link": "/chapters/chapter-03#h3_118"
                  },
                  {
                    "text": "گزینه ۳: Shadcn UI (کامپوننت‌های copy-paste)",
                    "link": "/chapters/chapter-03#h3_121"
                  }
                ],
                "link": "/chapters/chapter-03#h2_114"
              },
              {
                "text": "چرا Shadcn UI را انتخاب کردیم",
                "link": "/chapters/chapter-03#h2_124"
              },
              {
                "text": "پیکربندی Shadcn UI",
                "collapsed": true,
                "items": [
                  {
                    "text": "استفاده از CLI",
                    "link": "/chapters/chapter-03#h3_126"
                  },
                  {
                    "text": "افزودن کامپوننت‌ها",
                    "link": "/chapters/chapter-03#h3_127"
                  }
                ],
                "link": "/chapters/chapter-03#h2_125"
              },
              {
                "text": "ساخت دستی کامپوننت‌ها",
                "link": "/chapters/chapter-03#h2_128"
              }
            ],
            "link": "/chapters/chapter-03#h1_112"
          },
          {
            "text": "مستندسازی کامپوننت‌ها",
            "collapsed": true,
            "items": [
              {
                "text": "ساخت route کامپوننت",
                "link": "/chapters/chapter-03#h2_130"
              },
              {
                "text": "Storybook چیست؟",
                "link": "/chapters/chapter-03#h2_131"
              },
              {
                "text": "پیکربندی Storybook",
                "link": "/chapters/chapter-03#h2_132"
              },
              {
                "text": "پیکربندی Vite برای Storybook",
                "collapsed": true,
                "items": [
                  {
                    "text": "پیکربندی preview در Storybook",
                    "link": "/chapters/chapter-03#h3_134"
                  }
                ],
                "link": "/chapters/chapter-03#h2_133"
              },
              {
                "text": "اجرای Storybook",
                "link": "/chapters/chapter-03#h2_135"
              },
              {
                "text": "مستندسازی کامپوننت‌ها با Storybook",
                "collapsed": true,
                "items": [
                  {
                    "text": "ساخت فایل story",
                    "link": "/chapters/chapter-03#h3_137"
                  }
                ],
                "link": "/chapters/chapter-03#h2_136"
              },
              {
                "text": "مشاهده storyها در Storybook",
                "link": "/chapters/chapter-03#h2_141"
              }
            ],
            "link": "/chapters/chapter-03#h1_129"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-03#h1_142"
          }
        ]
      },
      {
        "text": "فصل ۴: مسیریابی و استراتژی‌های رندر",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-04"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-04#h1_146"
          },
          {
            "text": "مسیریابی با React Router",
            "collapsed": true,
            "items": [
              {
                "text": "پیکربندی routeها در React Router",
                "link": "/chapters/chapter-04#h2_148"
              },
              {
                "text": "ناوبری بین صفحات",
                "collapsed": true,
                "items": [
                  {
                    "text": "استفاده از Link برای ناوبری ساده",
                    "link": "/chapters/chapter-04#h3_150"
                  },
                  {
                    "text": "استفاده از NavLink برای ناوبری با active state",
                    "link": "/chapters/chapter-04#h3_151"
                  },
                  {
                    "text": "استفاده از useNavigate برای ناوبری programmatic",
                    "link": "/chapters/chapter-04#h3_152"
                  }
                ],
                "link": "/chapters/chapter-04#h2_149"
              }
            ],
            "link": "/chapters/chapter-04#h1_147"
          },
          {
            "text": "استراتژی‌های رندر",
            "collapsed": true,
            "items": [
              {
                "text": "Server-side rendering",
                "collapsed": true,
                "items": [
                  {
                    "text": "ساخت صفحه جزئیات idea با SSR",
                    "link": "/chapters/chapter-04#h3_155"
                  }
                ],
                "link": "/chapters/chapter-04#h2_154"
              },
              {
                "text": "Client-side rendering",
                "collapsed": true,
                "items": [
                  {
                    "text": "ساخت صفحه dashboard با CSR",
                    "link": "/chapters/chapter-04#h3_157"
                  }
                ],
                "link": "/chapters/chapter-04#h2_156"
              },
              {
                "text": "Hybrid rendering",
                "collapsed": true,
                "items": [
                  {
                    "text": "ساخت صفحه profile با hybrid rendering",
                    "link": "/chapters/chapter-04#h3_159"
                  }
                ],
                "link": "/chapters/chapter-04#h2_158"
              },
              {
                "text": "Static pre-rendering",
                "collapsed": true,
                "items": [
                  {
                    "text": "ساخت صفحات home و about با pre-rendering",
                    "link": "/chapters/chapter-04#h3_161"
                  }
                ],
                "link": "/chapters/chapter-04#h2_160"
              }
            ],
            "link": "/chapters/chapter-04#h1_153"
          },
          {
            "text": "افزودن meta tag به صفحات",
            "link": "/chapters/chapter-04#h1_162"
          },
          {
            "text": "افزودن layout صفحات",
            "link": "/chapters/chapter-04#h1_163"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-04#h1_164"
          }
        ]
      },
      {
        "text": "فصل ۵: ارتباط با API",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-05"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-05#h1_168"
          },
          {
            "text": "ساخت API client",
            "link": "/chapters/chapter-05#h1_169"
          },
          {
            "text": "تولید type و schema اعتبارسنجی TypeScript از مشخصات OpenAPI",
            "collapsed": true,
            "items": [
              {
                "text": "OpenAPI چیست و چرا type تولید کنیم؟",
                "link": "/chapters/chapter-05#h2_171"
              },
              {
                "text": "پیکربندی تولید type",
                "link": "/chapters/chapter-05#h2_172"
              }
            ],
            "link": "/chapters/chapter-05#h1_170"
          },
          {
            "text": "راه‌اندازی React Query",
            "collapsed": true,
            "items": [
              {
                "text": "چرا React Query؟",
                "link": "/chapters/chapter-05#h2_174"
              },
              {
                "text": "پیکربندی React Query برای اپلیکیشن",
                "link": "/chapters/chapter-05#h2_175"
              }
            ],
            "link": "/chapters/chapter-05#h1_173"
          },
          {
            "text": "ساخت لایه API برای اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "سازمان‌دهی query keyها",
                "link": "/chapters/chapter-05#h2_177"
              },
              {
                "text": "تعریف queryها",
                "link": "/chapters/chapter-05#h2_178"
              },
              {
                "text": "تعریف mutationها",
                "link": "/chapters/chapter-05#h2_179"
              }
            ],
            "link": "/chapters/chapter-05#h1_176"
          },
          {
            "text": "یکپارچه‌سازی با اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "Queryها",
                "collapsed": true,
                "items": [
                  {
                    "text": "استفاده سمت client",
                    "link": "/chapters/chapter-05#h3_182"
                  },
                  {
                    "text": "استفاده سمت server",
                    "link": "/chapters/chapter-05#h3_183"
                  },
                  {
                    "text": "استفاده سمت server با HydrationBoundary",
                    "link": "/chapters/chapter-05#h3_184"
                  }
                ],
                "link": "/chapters/chapter-05#h2_181"
              },
              {
                "text": "Mutationها",
                "link": "/chapters/chapter-05#h2_185"
              }
            ],
            "link": "/chapters/chapter-05#h1_180"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-05#h1_186"
          }
        ]
      },
      {
        "text": "فصل ۶: مدیریت state اپلیکیشن",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-06"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-06#h1_190"
          },
          {
            "text": "مدیریت state محلی",
            "link": "/chapters/chapter-06#h1_191"
          },
          {
            "text": "اشتراک‌گذاری state سراسری",
            "link": "/chapters/chapter-06#h1_192"
          },
          {
            "text": "مدیریت state ناهمگام",
            "link": "/chapters/chapter-06#h1_193"
          },
          {
            "text": "مدیریت state فرم",
            "link": "/chapters/chapter-06#h1_194"
          },
          {
            "text": "پایدارسازی state در URL",
            "link": "/chapters/chapter-06#h1_195"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-06#h1_196"
          }
        ]
      },
      {
        "text": "فصل ۷: پیاده‌سازی احراز هویت و امن‌سازی اپلیکیشن",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-07"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-07#h1_200"
          },
          {
            "text": "احراز هویت",
            "collapsed": true,
            "items": [
              {
                "text": "گسترش API client",
                "link": "/chapters/chapter-07#h2_202"
              },
              {
                "text": "صفحه ثبت‌نام",
                "link": "/chapters/chapter-07#h2_203"
              },
              {
                "text": "صفحه ورود",
                "link": "/chapters/chapter-07#h2_204"
              },
              {
                "text": "خروج کاربر",
                "link": "/chapters/chapter-07#h2_205"
              },
              {
                "text": "دسترسی به کاربر در اپلیکیشن",
                "link": "/chapters/chapter-07#h2_206"
              },
              {
                "text": "محافظت از routeها",
                "link": "/chapters/chapter-07#h2_207"
              }
            ],
            "link": "/chapters/chapter-07#h1_201"
          },
          {
            "text": "مجوزدهی",
            "link": "/chapters/chapter-07#h1_208"
          },
          {
            "text": "امن‌سازی اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "Sanitization محتوا",
                "link": "/chapters/chapter-07#h2_210"
              },
              {
                "text": "Security headerها",
                "link": "/chapters/chapter-07#h2_211"
              }
            ],
            "link": "/chapters/chapter-07#h1_209"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-07#h1_212"
          }
        ]
      },
      {
        "text": "فصل ۸: بهبود عملکرد اپلیکیشن",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-08"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-08#h1_216"
          },
          {
            "text": "شناسایی مشکلات عملکرد",
            "link": "/chapters/chapter-08#h1_217"
          },
          {
            "text": "بهینه‌سازی کامپوننت‌ها",
            "collapsed": true,
            "items": [
              {
                "text": "Colocation state",
                "link": "/chapters/chapter-08#h2_219"
              },
              {
                "text": "Memoize کردن محاسبات سنگین",
                "link": "/chapters/chapter-08#h2_220"
              },
              {
                "text": "استفاده از component composition",
                "link": "/chapters/chapter-08#h2_221"
              },
              {
                "text": "Code splitting و lazy loading",
                "link": "/chapters/chapter-08#h2_222"
              }
            ],
            "link": "/chapters/chapter-08#h1_218"
          },
          {
            "text": "Streaming محتوا از server",
            "link": "/chapters/chapter-08#h1_223"
          },
          {
            "text": "Debouncing ورودی کاربر",
            "link": "/chapters/chapter-08#h1_224"
          },
          {
            "text": "بهینه‌سازی dataset بزرگ",
            "collapsed": true,
            "items": [
              {
                "text": "صفحه‌بندی",
                "link": "/chapters/chapter-08#h2_226"
              }
            ],
            "link": "/chapters/chapter-08#h1_225"
          },
          {
            "text": "Virtualization لیست",
            "link": "/chapters/chapter-08#h1_227"
          },
          {
            "text": "Optimistic update",
            "link": "/chapters/chapter-08#h1_228"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-08#h1_229"
          }
        ]
      },
      {
        "text": "فصل ۹: بین‌المللی‌سازی",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-09"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-09#h1_233"
          },
          {
            "text": "درک معماری بین‌المللی‌سازی",
            "collapsed": true,
            "items": [
              {
                "text": "محل ذخیره ترجمه‌ها",
                "link": "/chapters/chapter-09#h2_235"
              },
              {
                "text": "نحوه کار سیستم i18n ما",
                "collapsed": true,
                "items": [
                  {
                    "text": "تشخیص و ذخیره زبان",
                    "link": "/chapters/chapter-09#h3_237"
                  },
                  {
                    "text": "SSR همراه با ترجمه",
                    "link": "/chapters/chapter-09#h3_238"
                  },
                  {
                    "text": "Hydration سمت client",
                    "link": "/chapters/chapter-09#h3_239"
                  },
                  {
                    "text": "بارگذاری پویا ترجمه‌ها",
                    "link": "/chapters/chapter-09#h3_240"
                  },
                  {
                    "text": "تعویض زبان",
                    "link": "/chapters/chapter-09#h3_241"
                  }
                ],
                "link": "/chapters/chapter-09#h2_236"
              }
            ],
            "link": "/chapters/chapter-09#h1_234"
          },
          {
            "text": "راه‌اندازی i18n در اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "سازمان‌دهی ترجمه‌ها با namespace",
                "collapsed": true,
                "items": [
                  {
                    "text": "ترجمه‌های سطح app",
                    "link": "/chapters/chapter-09#h3_244"
                  },
                  {
                    "text": "ترجمه‌های محدود به feature",
                    "link": "/chapters/chapter-09#h3_245"
                  },
                  {
                    "text": "ترکیب ترجمه‌ها",
                    "link": "/chapters/chapter-09#h3_246"
                  }
                ],
                "link": "/chapters/chapter-09#h2_243"
              },
              {
                "text": "پیکربندی React-i18next",
                "collapsed": true,
                "items": [
                  {
                    "text": "ساخت middleware در i18next",
                    "link": "/chapters/chapter-09#h3_248"
                  },
                  {
                    "text": "مقداردهی اولیه روی server",
                    "link": "/chapters/chapter-09#h3_249"
                  },
                  {
                    "text": "مقداردهی اولیه روی client",
                    "link": "/chapters/chapter-09#h3_250"
                  }
                ],
                "link": "/chapters/chapter-09#h2_247"
              },
              {
                "text": "سرو ترجمه‌ها از طریق API",
                "link": "/chapters/chapter-09#h2_251"
              },
              {
                "text": "افزودن type safety به کلیدهای ترجمه",
                "link": "/chapters/chapter-09#h2_252"
              }
            ],
            "link": "/chapters/chapter-09#h1_242"
          },
          {
            "text": "استفاده از ترجمه‌ها در اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "استفاده از namespace پیش‌فرض",
                "link": "/chapters/chapter-09#h2_254"
              },
              {
                "text": "Interpolation",
                "link": "/chapters/chapter-09#h2_255"
              },
              {
                "text": "Pluralization",
                "link": "/chapters/chapter-09#h2_256"
              },
              {
                "text": "قالب‌بندی تاریخ",
                "link": "/chapters/chapter-09#h2_257"
              }
            ],
            "link": "/chapters/chapter-09#h1_253"
          },
          {
            "text": "تعویض زبان در اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "کامپوننت language switcher",
                "link": "/chapters/chapter-09#h2_259"
              },
              {
                "text": "endpoint مربوط به API",
                "link": "/chapters/chapter-09#h2_260"
              }
            ],
            "link": "/chapters/chapter-09#h1_258"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-09#h1_261"
          }
        ]
      },
      {
        "text": "فصل ۱۰: دسترس‌پذیر کردن اپلیکیشن",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-10"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-10#h1_265"
          },
          {
            "text": "درک اصول دسترس‌پذیری",
            "collapsed": true,
            "items": [
              {
                "text": "اصول accessibility",
                "link": "/chapters/chapter-10#h2_267"
              }
            ],
            "link": "/chapters/chapter-10#h1_266"
          },
          {
            "text": "ایجاد بنیان معماری",
            "collapsed": true,
            "items": [
              {
                "text": "Semantic HTML",
                "collapsed": true,
                "items": [
                  {
                    "text": "تعریف landmark صفحات",
                    "link": "/chapters/chapter-10#h3_270"
                  }
                ],
                "link": "/chapters/chapter-10#h2_269"
              },
              {
                "text": "استفاده از کتابخانه کامپوننت accessible",
                "link": "/chapters/chapter-10#h2_271"
              }
            ],
            "link": "/chapters/chapter-10#h1_268"
          },
          {
            "text": "بهینه‌سازی‌های عملی accessibility",
            "collapsed": true,
            "items": [
              {
                "text": "Skip link برای ناوبری با keyboard",
                "link": "/chapters/chapter-10#h2_273"
              },
              {
                "text": "ارائه labelهای accessible",
                "link": "/chapters/chapter-10#h2_274"
              },
              {
                "text": "اعلام تغییرات پویا",
                "link": "/chapters/chapter-10#h2_275"
              }
            ],
            "link": "/chapters/chapter-10#h1_272"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-10#h1_276"
          }
        ]
      },
      {
        "text": "فصل ۱۱: تست اپلیکیشن",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-11"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-11#h1_280"
          },
          {
            "text": "چرا تست مهم است",
            "link": "/chapters/chapter-11#h1_281"
          },
          {
            "text": "Unit testing",
            "link": "/chapters/chapter-11#h1_282"
          },
          {
            "text": "Integration testing",
            "link": "/chapters/chapter-11#h1_283"
          },
          {
            "text": "End-to-end testing",
            "link": "/chapters/chapter-11#h1_284"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-11#h1_285"
          }
        ]
      },
      {
        "text": "فصل ۱۲: استقرار در Production",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-12"
          },
          {
            "text": "پیش‌نیازهای فنی",
            "link": "/chapters/chapter-12#h1_289"
          },
          {
            "text": "CI/CD چیست؟",
            "link": "/chapters/chapter-12#h1_290"
          },
          {
            "text": "استفاده از GitHub Actions",
            "collapsed": true,
            "items": [
              {
                "text": "Workflowها",
                "link": "/chapters/chapter-12#h2_292"
              },
              {
                "text": "Eventها",
                "link": "/chapters/chapter-12#h2_293"
              },
              {
                "text": "Jobها",
                "link": "/chapters/chapter-12#h2_294"
              },
              {
                "text": "Stepها",
                "link": "/chapters/chapter-12#h2_295"
              },
              {
                "text": "Actionها",
                "link": "/chapters/chapter-12#h2_296"
              },
              {
                "text": "Runnerها",
                "link": "/chapters/chapter-12#h2_297"
              }
            ],
            "link": "/chapters/chapter-12#h1_291"
          },
          {
            "text": "پیکربندی pipeline برای continuous integration",
            "link": "/chapters/chapter-12#h1_298"
          },
          {
            "text": "پیکربندی pipeline برای continuous deployment",
            "collapsed": true,
            "items": [
              {
                "text": "ساخت workflow استقرار",
                "link": "/chapters/chapter-12#h2_300"
              },
              {
                "text": "راه‌اندازی Render",
                "link": "/chapters/chapter-12#h2_301"
              },
              {
                "text": "دریافت service ID و API key",
                "link": "/chapters/chapter-12#h2_302"
              },
              {
                "text": "افزودن secretها به repository",
                "link": "/chapters/chapter-12#h2_303"
              },
              {
                "text": "تأیید استقرار",
                "link": "/chapters/chapter-12#h2_304"
              }
            ],
            "link": "/chapters/chapter-12#h1_299"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-12#h1_305"
          }
        ]
      },
      {
        "text": "فصل ۱۳: تکامل اپلیکیشن",
        "collapsed": true,
        "items": [
          {
            "text": "نمای کلی",
            "link": "/chapters/chapter-13"
          },
          {
            "text": "استفاده از AI برای اعمال معماری اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "درک mental model درست",
                "link": "/chapters/chapter-13#h2_310"
              },
              {
                "text": "فایل‌های context",
                "link": "/chapters/chapter-13#h2_311"
              },
              {
                "text": "نوشتن ruleهای مؤثر",
                "link": "/chapters/chapter-13#h2_312"
              },
              {
                "text": "موارد کاربرد عملی",
                "link": "/chapters/chapter-13#h2_313"
              },
              {
                "text": "به‌روز نگه‌داشتن ruleها",
                "link": "/chapters/chapter-13#h2_314"
              }
            ],
            "link": "/chapters/chapter-13#h1_309"
          },
          {
            "text": "React Server Components",
            "collapsed": true,
            "items": [
              {
                "text": "چرا Server Component؟",
                "link": "/chapters/chapter-13#h2_316"
              }
            ],
            "link": "/chapters/chapter-13#h1_315"
          },
          {
            "text": "Monitoring و observability اپلیکیشن",
            "collapsed": true,
            "items": [
              {
                "text": "ردیابی خطا با Sentry",
                "link": "/chapters/chapter-13#h2_318"
              },
              {
                "text": "Monitoring عملکرد",
                "link": "/chapters/chapter-13#h2_319"
              },
              {
                "text": "Logging ساخت‌یافته و alertها",
                "link": "/chapters/chapter-13#h2_320"
              }
            ],
            "link": "/chapters/chapter-13#h1_317"
          },
          {
            "text": "Feature flag",
            "collapsed": true,
            "items": [
              {
                "text": "پیاده‌سازی ساده در برابر ابزار اختصاصی",
                "link": "/chapters/chapter-13#h2_322"
              },
              {
                "text": "A/B testing",
                "link": "/chapters/chapter-13#h2_323"
              }
            ],
            "link": "/chapters/chapter-13#h1_321"
          },
          {
            "text": "مقیاس‌پذیری لایه API",
            "collapsed": true,
            "items": [
              {
                "text": "الگوی BFF",
                "link": "/chapters/chapter-13#h2_325"
              }
            ],
            "link": "/chapters/chapter-13#h1_324"
          },
          {
            "text": "Monorepo",
            "collapsed": true,
            "items": [
              {
                "text": "اشتراک package بین appها",
                "link": "/chapters/chapter-13#h2_327"
              }
            ],
            "link": "/chapters/chapter-13#h1_326"
          },
          {
            "text": "Microfrontend",
            "collapsed": true,
            "items": [
              {
                "text": "چه زمانی microfrontend منطقی است",
                "link": "/chapters/chapter-13#h2_329"
              },
              {
                "text": "Trade-offهایی که قبل از پذیرش باید بدانید",
                "link": "/chapters/chapter-13#h2_330"
              }
            ],
            "link": "/chapters/chapter-13#h1_328"
          },
          {
            "text": "خلاصه",
            "link": "/chapters/chapter-13#h1_331"
          }
        ]
      }
    ]
  }
]
